# Generated by Django 5.1.7 on 2025-04-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maaun', '0003_voter_has_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='photo',
        ),
        migrations.AddField(
            model_name='candidate',
            name='avater',
            field=models.ImageField(default='avater.png', null=True, upload_to=''),
        ),
    ]
