# Generated by Django 5.2.1 on 2025-05-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maaun', '0006_alter_election_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='year',
            field=models.IntegerField(max_length=4, unique=True),
        ),
    ]
