# Generated by Django 5.2.1 on 2025-05-11 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maaun', '0007_alter_election_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='year',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
